### ISSUE TITLE
Binary XML file line #9: Error inflating class me.amiee.nicetab.NiceTabLayout

### ISSUE THREAD

**Issue by vanchung** [RobotAmiee/Android-NiceTab#4]
Process: com.example.milispace.milispace, PID: 13101
                                                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.milispace.milispace/com.dreamm.Milispace.view.slidemenu.MilispaceSlideMenu}: android.view.InflateException: Binary XML file line #9: Error inflating class me.amiee.nicetab.NiceTabLayout
                                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2525)
                                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2617)
                                                                                     at android.app.ActivityThread.access$800(ActivityThread.java:182)
                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1474)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                                     at android.os.Looper.loop(Looper.java:218)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5657)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:990)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:785)
                                                                                  Caused by: android.view.InflateException: Binary XML file line #9: Error inflating class me.amiee.nicetab.NiceTabLayout
                                                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:633)
                                                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
                                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
                                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
                                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
                                                                                     at com.dreamm.Milispace.view.slidingtab.StartNiceTab.onCreateView(StartNiceTab.java:46)
                                                                                     at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)
                                                                                     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
                                                                                     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
                                                                                     at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:742)
                                                                                     at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
                                                                                     at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:339)
                                                                                     at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:602)
                                                                                     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1244)
                                                                                     at android.app.Activity.performStart(Activity.java:6151)
                                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2482)
                                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2617) 
                                                                                     at android.app.ActivityThread.access$800(ActivityThread.java:182) 
                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1474) 
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                                     at android.os.Looper.loop(Looper.java:218) 
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5657) 
                                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                                     at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:990) 
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:785) 
                                                                                  Caused by: java.lang.reflect.InvocationTargetException
                                                                                     at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                                     at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
                                                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:607)
                                                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743) 
                                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
                                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
                                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
                                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
                                                                                     at com.dreamm.Milispace.view.slidingtab.StartNiceTab.onCreateView(StartNiceTab.java:46) 
                                                                                     at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974) 
                                                                                     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067) 
                                                                                     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252) 
                                                                                     at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:742) 
                                                                                     at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617) 
                                                                                     at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:339) 
                                                                                     at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:602) 
                                                                                     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1244) 
                                                                                     at android.app.Activity.performStart(Activity.java:6151) 
                                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2482) 
                                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2617) 
                                                                                     at android.app.ActivityThread.access$800(ActivityThread.java:182) 
                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1474) 
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                                     at android.os.Looper.loop(Looper.java:218) 
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5657) 
                                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                                     at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:990) 
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:785) 
                                                                                  Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v8/renderscript/RenderScript;
                                                                                     at me.amiee.nicetab.NiceTabStrip.initRenderScript(NiceTabStrip.java:544)
                                                                                     at me.amiee.nicetab.NiceTabStrip.<init>(NiceTabStrip.java:502)
                                                                                     at me.amiee.nicetab.NiceTabLayout.<init>(NiceTabLayout.java:194)
                                                                                     at me.amiee.nicetab.NiceTabLayout.<init>(NiceTabLayout.java:133)
                                                                                     at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                                     at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
                                                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:607) 
                                                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743) 
                                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
                                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
                                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
                                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
                                                                                     at com.dreamm.Milispace.view.slidingtab.StartNiceTab.onCreateView(StartNiceTab.java:46) 
                                                                                     at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974) 
                                                                                     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067) 
                                                                                     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252) 
                                                                                     at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:742) 
                                                                                     at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617) 
                                                                                     at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:339) 
                                                                                     at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:602) 
                                                                                     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1244) 
                                                                                     at android.app.Activity.performStart(Activity.java:6151) 
                                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2482) 
                                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2617) 
                                                                                     at android.app.ActivityThread.access$800(ActivityThread.java:182) 
                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1474) 
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                                     at android.os.Looper.loop(Looper.java:218) 
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5657) 
                                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                                     at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:990) 
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:785) 
                                                                                  Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v8.renderscript.RenderScript" on path: DexPathList[[dex file "/data/data/com.example.milispace.milispace/files/instant-run/dex/slice-zip4j-1.3.2_f728f80ccf711e45ce184a9c1b90868a8c287ed9-classes.dex", dex file "/data/data/com.example.milispace.milispace/files/instant-run/dex/slice-universal-image-loader-1.9.3_c0a769fce08f3876d58b638cd3cf59c11e0d5448-classes.dex", dex file "/data/data/com.example.milispace.milispace/files/instant-run/dex/slice-systembartint-1.0.3_79084032bdf4831b4792a45df467e6d485629218-classes.dex", dex file "/data/data/com.example.milispace.milispace/files/instant-run/dex/slice-support-annotations-23.3.0_5f3c49fb8cf92a86f170212d7084646ffc9e0982-classes.dex", dex file "/data/data/com.example.milispace.milispace/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/com.example.milispace.milispace

**Comment by M-yeganehh** [comment]
same issue here

**Comment by filnik** [comment]
same here. Any idea of how to fix this?
